services:
  hugot-test:
    platform: linux/amd64
    image: hugot-test:latest
    container_name: hugot-test
    volumes:
      - $test_folder:/testTarget
    environment:
      - HOST_UID=$host_uid
      - CI=$CI
    command: /run-unit-tests-container.sh
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
